### ISSUE TITLE
window.devicePixelRatio results RangeError

### ISSUE THREAD

**Issue by qinlili23333** [meowtec/audio-cutter#10]
> index.js:9 Uncaught (in promise) RangeError: Invalid array length
>     at e.default (index.js:9:65609)
>     at e.value (index.js:9:63143)
>     at e.value (index.js:9:62719)
>     at performInitialMount (react.min.js:13:13299)
>     at p.mountComponent (react.min.js:13:12467)
>     at Object.mountComponent (react.min.js:15:2892)
>     at h.mountChildren (react.min.js:14:26368)
>     at h._createInitialChildren (react.min.js:13:26619)
>     at h.mountComponent (react.min.js:13:24771)
>     at Object.mountComponent (react.min.js:15:2892)

it is due to window.devicePixelRatio returns 1.6500000953674316 so that the value in new Array() is not integer

**Comment by qinlili23333** [comment]
This is my temp fix https://github.com/qinlili23333/audio-cutter/commit/2986b6c13bd6901f4fee56ca07b4a067d8688470
maybe there can be sth better

**Comment by meowtec** [comment]
Please checkout a new branch (or rebase) based at `next`: https://github.com/meowtec/audio-cutter/tree/next
The fix should move here: https://github.com/meowtec/audio-cutter/blob/next/src/waver.tsx#L30

And welcome for Pull Request

**Comment by qinlili23333** [comment]
> Please checkout a new branch (or rebase) based at `next`: https://github.com/meowtec/audio-cutter/tree/next The fix should move here: https://github.com/meowtec/audio-cutter/blob/next/src/waver.tsx#L30
> 
> And welcome for Pull Request

 new branch works fine with no modification. however the select music button at left bottom dosen't work and got white screen 

```
   react-dom.production.min.js:141 TypeError: Cannot read properties of null (reading 'duration')
    at $ (index.js:formatted:1472:32)
    at Le (react-dom.production.min.js:100:3)
    at Re (react-dom.production.min.js:113:271)
    at Pj (react-dom.production.min.js:233:55)
    at di (react-dom.production.min.js:168:305)
    at Nj (react-dom.production.min.js:168:236)
    at sc (react-dom.production.min.js:168:96)
    at gf (react-dom.production.min.js:162:109)
    at react-dom.production.min.js:73:230
    at unstable_runWithPriority (react.production.min.js:24:26) 
```
