### ISSUE TITLE
无法生成截取的mp3

### ISSUE THREAD

**Issue by qinshulei** [meowtec/audio-cutter#2]
Uncaught RangeError: Invalid typed array length: undefined
    at typedArrayConstructByArrayBuffer (<anonymous>)
    at new Int8Array (native)
    at https://meowtec.github.io/audio-cutter/vendor/Mp3LameEncoder.min.js:1:22292
    at https://meowtec.github.io/audio-cutter/vendor/Mp3LameEncoder.min.js:14:31938
    at Object.<anonymous> (https://meowtec.github.io/audio-cutter/dist/worker.js:1:2120)
    at t (https://meowtec.github.io/audio-cutter/dist/worker.js:1:101)
    at Object.<anonymous> (https://meowtec.github.io/audio-cutter/dist/worker.js:1:566)
    at t (https://meowtec.github.io/audio-cutter/dist/worker.js:1:101)
    at https://meowtec.github.io/audio-cutter/dist/worker.js:1:455
    at https://meowtec.github.io/audio-cutter/dist/worker.js:1:464
Mp3LameEncoder.min.js:1 Uncaught RangeError: Invalid typed array length: undefined

**Comment by linwenfeng122** [comment]
> 复现步骤？

在搜狗浏览器下面就会这样
